services:
  claudecode:
    build:
      context: .
      dockerfile: claudecode/Dockerfile
    container_name: claudecode-stdio
    user: root  
    volumes:
      - ${WORKSPACE_PATH:-./workspace}:/workspace
    ports:
      - "${HOST_PORT:-9999}:${CONTAINER_PORT:-9999}"
    restart: unless-stopped
    stdin_open: true 

