services:
  claudecode:
    build:
      context: .
      dockerfile: Dockerfile_claude_code_sse
    container_name: claudecode-stdio
    user: root  
    volumes:
      - ${WORKSPACE_PATH:-./workspace}:/workspace
    ports:
      - "${HOST_PORT:-9999}:${CONTAINER_PORT:-9999}"
    restart: unless-stopped
    stdin_open: true 

  tavily:
    build:
      context: .
      dockerfile: Dockerfile_tavily
    container_name: tavily-mcp
    restart: unless-stopped
    stdin_open: true 
    env_file:
      - .env